- name: Setup .NET Core SDK
  uses: actions/setup-dotnet@v1.7.2
  with:
    # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
    dotnet-version: # optional
    # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword
    source-url: # optional
    # Optional OWNER for using packages from GitHub Package Registry organizations/users other than the current repository's owner. Only used if a GPR URL is also provided in source-url
    owner: # optional
    # Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo.
    config-file: # optional

BaesBeat/ .github/workflows/
1

- name: Setup .NET Core SDK

2

  uses: actions/setup-dotnet@v1.7.2

3

  with:

4

    # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x

5

    dotnet-version: # optional

6

    # Optional package source for which to set up authentication. Will consult any existing NuGet.config in the root of the repo and provide a temporary NuGet.config using the NUGET_AUTH_TOKEN environment variable as a ClearTextPassword

7

    source-url: # optional

8

    # Optional OWNER for using packages from GitHub Package Registry organizations/users other than the current repository's owner. Only used if a GPR URL is also provided in source-url

9

    owner: # optional

10

    # Optional NuGet.config location, if your NuGet.config isn't located in the root of the repo.

11

    config-file: # optional

12

​

Use Control + Space to trigger autoc
